server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/yangstars/spring-cloud
          #配置仓库路径
          searchPaths: respo
          username: 951020602@qq.com
          password: moxiao1990
      #配置仓库的分支
      label: master


